apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-files-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;

    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        #access_log /var/log/nginx/access.log main;
        #error_log /var/log/nginx/error.log warn;
        # Set the access log to STDOUT
        access_log /dev/stdout;
        # Set the error log to STDERR
        error_log /dev/stderr warn;
        
        server {
            listen 8080;
            server_name {{ .Values.appname_files }}.apps.{{ .Values.okdcluster }};
           
            location / {
                root /usr/share/nginx/html;  # Serve files from this directory
                # REMOVE Cache-Control from backend
                proxy_hide_header Cache-Control;
                # Add Cache-Control header to the response
                add_header Cache-Control {{ .Values.nginx_cache_control_value | quote }};
            }
        }
 
             
        server {
            listen 8443 ssl;  # Listening on port 8443
            server_name {{ .Values.appname_files }}.apps.{{ .Values.okdcluster }};

            ssl_certificate /etc/grid-security/tls.crt;
            ssl_certificate_key /etc/grid-security/tls.key;
            ssl_protocols TLSv1.2 TLSv1.3;
            ssl_ciphers HIGH:!aNULL:!MD5;
            ssl_prefer_server_ciphers on;

            # Enable SSL verification (only if required)
            #ssl_verify_client on;
            #ssl_client_certificate /etc/grid-security/wildcard.bundle.sdcc.bnl.gov.pem; # CA Cert

            location / {
                root /usr/share/nginx/html;  # Serve files from this directory
                # REMOVE Cache-Control from backend
                proxy_hide_header Cache-Control;
                # Add Cache-Control header to the response
                add_header Cache-Control {{ .Values.nginx_cache_control_value | quote }};
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-files
  labels:
    app: nginx-files
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-files
  template:
    metadata:
      labels:
        app: nginx-files
    spec:
      securityContext:
        runAsUser: 101  # Default NGINX user
        fsGroup: 1000860000  # Match the group of the secret
      volumes:
        - name: files-volume
          persistentVolumeClaim:
            claimName: {{ .Values.pvc_payload_server}}
        - name: nginx-config-volume
          configMap:
            name: nginx-files-conf
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-pid
          emptyDir: {}
        - name: grid-cert-volume
          secret:
            secretName: nginx-grid-cert
      containers:
        - name: nginx
          image: "image-registry.openshift-image-registry.svc:5000/{{ .Values.project }}/nginx:{{ .Values.nginx_docker_image | splitList ":" | last }}"
          imagePullPolicy: IfNotPresent
#        - name: nginx
#          image: ' nginx:1.23.1-perl'
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          volumeMounts:
            - name: files-volume
              mountPath: /usr/share/nginx/html
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-pid
              mountPath: /var/run
            #oc create secret tls nginx-grid-cert --cert=/.../wildcard.bundle.domain.pem --key=/.../wildcard.bundle.domain.pem
            - name: grid-cert-volume 
              mountPath: /etc/grid-security
              readOnly: true
          imagePullPolicy: IfNotPresent
---
kind: Service
apiVersion: v1
metadata:
  name: "nginx-files"
spec:
  selector:
    app: "nginx-files"
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
  type: ClusterIP
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: nginx-files-https
  labels:
    app: nginx-files
  annotations:
    haproxy.router.openshift.io/disable_cookies: "true"
spec:
  host: {{ .Values.appname_files }}.apps.{{ .Values.okdcluster }}
  to:
    kind: Service
    name: nginx-files
  port:
#    targetPort: https
#  tls:
#    termination: passthrough
#    insecureEdgeTerminationPolicy: Redirect
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
