{{- if .Values.storage.payload.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "npdbchart.payloadClaimName" . }}
  labels:
    {{- include "npdbchart.labels" . | nindent 4 }}
    app.kubernetes.io/component: payload-storage
spec:
  accessModes:
    {{- toYaml .Values.storage.payload.accessModes | nindent 4 }}
  {{- with .Values.storage.payload.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.payload.size | quote }}
{{- end }}
